### ISSUE TITLE
条件を選びます画面の不具合修正

### ISSUE THREAD

**Issue by yumayuma708** [yumayuma708/flutter-cooking-app#37]
## ToDo

- [x] 指定しないが複数選ばれるバグの修正
- [x] 調理時間が選ばれなかった場合は「指定しない」が選ばれたことにする
- [x] 同じことを「タイプ・量・その他の条件」で設定
- [x] 人数は「1人分」になるように設定
- [x] その他の食材を含めるかが選択されなかった場合は「はい」が選ばれるように設定
