### ISSUE TITLE
Cooking Result改良データ編

### ISSUE THREAD

**Issue by yumayuma708** [yumayuma708/flutter-cooking-app#56]
## ToDo

- [x] renewボタンを作る
- [x] renewを押したらもう一度レシピを生成するように設定
- [x] Firebaseを使用するためのパッケージの導入
- [x] 保存ボタンを押したら「レシピを保存しました」とポップアップが出るようにする。
- [x] ポップアップのUIをデザインする
- [x] ポップアップのアーキテクチャを整備する。
- [x] ログインしていない時のsave_screenのUIを整備
- [x] マイページにappBarをつける、UIの変更
- [x] マイページのログイン、サインイン、ログアウトボタンのUIの整備
- [x] これらのポップアップのUIも整備
- [x] ログインしていない時、ログインしている時に応じて、表示するボタンを変更する。
